apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet18-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resnet18-inference
  template:
    metadata:
      labels:
        app: resnet18-inference
    spec:
      containers:
      - name: resnet18-inference
        image: abm1499/resnet18-inference:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"