apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: resnet18-hpa-50
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: resnet18-inference
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50