apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'resnet18-inference'
        static_configs:
          - targets: ['resnet18-inference.default.svc.cluster.local:8000']