apiVersion: v1
kind: Service
metadata:
  name: resnet18-inference
spec:
  selector:
    app: resnet18-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007
  type: NodePort
